# Generated by Django 3.1.12 on 2025-01-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hospital',
            field=models.ForeignKey(blank=True, db_column='hospital_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='document.hospital'),
        ),
    ]
